# Javascript Node CircleCI 2.0 configuration file
version: 2
executors:
  publisher:
    docker:
      - image: circleci/node:10
jobs:
  install:
    executors: publisher
    steps:
      - checkout
      - run:
        name: install dependencies
        command: 
          npm install
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo

  test_phase: 
    executors: publisher
    steps:
      - run:
        name: test project
        # run tests!
        command: 
          npm run test
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

  build_image:
    steps: 
      - run:
          name: build and tag the image
          command: |
              docker build -f Node/Dockerfile 
              docker build -t htysn21/api:latest
      - run:
         name: publish image to docker hub
         command: |
             docker login -u "hugotysn21" -p
             docker push htysn21/api:latest


workflows:
  version: 2
  dev:
    jobs:
      - install:
        filters:
          branches:
            only: dev
      - test_phase:
          requires:
            - install
          filters:
            branches:
              only: dev
      - build_image:
          - test_phase
            filters:
              branches:
                only: dev





