# Javascript Node CircleCI 2.0 configuration file
version: 2.1

executors:
  publisher:
    docker:
      - image: circleci/node:10

jobs:
  install:
    executor: publisher
    steps:
      - checkout
      - run:
          name: install dependencies
          command: 
              npm install

  test_phase: 
    executor: publisher
    steps:
      - run:
          name: run test project
          command: 
              npm run test
      - run:    
          name: Creating Dummy Artifacts
          command: |
              echo "my artifact file" > /tmp/artifact-1;
              mkdir /tmp/artifacts;
              echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts    

  build_image:
    executor: publisher
    steps: 
      - run:
          name: build and tag the image
          command: |
              docker build -f Node/Dockerfile 
              docker build -t htysn21/api:latest
      - run:
          name: publish image to docker hub
          command: |
              docker login -u "hugotysn21" -p
              docker push htysn21/api:latest

workflows:
  version: 2
  dev:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test_phase:
          requires:
            - install
          filters:
            branches:
              only: master
      - build_image:
          requires:
            - test_phase
          filters:
            branches:
              only: master

#  prod:
#    jobs:
#      - install:
#          filters:
#            tag:
#              only: master
#      - test_phase:
#          requires:
#            - install
#          filters:
#            branches:
#              only: dev
#      - build_image:
#          requires:
#            - test_phase
#          filters:
#            branches:
#              only: master